### ISSUE TITLE
Sequence format

### ISSUE THREAD

**Issue by faymanns** [IBT-FMI/COSgen#1]
The tsv format specified by BIDS seems like the logical choice. However, it is not clear how a sequence of that format should be handled by the genetic algorithm.
I see two options here:

1. We write write rather complex cross_over and mutate functions.
2. We use a different format internally and write a function that converts our format to the BIDS format.

**Comment by TheChymera** [comment]
I see no reason to use the BIDS format internally. After all, BIDS is just a standard, the output format may be changed or parameterized at any point. The internal structure should be what best suits the optimization operations.
