### ISSUE TITLE
Baseline

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSgen#2]
As discussed earlier, to dispel concerns about (highly improbable) confounding activity at the stimulus frequency and phase-locked with the stimulus, it would be good to have a parameter where a desired baseline length can be specified. Additionally, the parameter could also take a string, `"auto"` which sets the baseline at e.g. the period of the maximum amplitude frequency (which is what we generally do atm).

**Comment by faymanns** [comment]
Implemented in a8e20ba0f5b6cfbf05e505f4862f9dd110f6eaaa
